### ISSUE TITLE
Documentation request: state the intended audience at the top of the description

### ISSUE THREAD

**Issue by DanKaplanSES** [idahogurl/vs-code-prettier-eslint#194]
In the Visual Studio Code extension tab, searching for "prettier" or "eslint" returns this extension as the 2nd result. As someone trying to figure out which of these three I should be installing, this is my thought process: 

> I use prettier in my project. I also use eslint. Should I be installing this extension or the two at the top of the search results? Or maybe I should be installing all three?

I've done a little googling and I think this extension is meant for projects using [prettier-eslint](https://github.com/prettier/prettier-eslint) as opposed to *every* project using prettier and eslint. If this is the case, can that be added to the top of the extension description so it's quicker to learn if it's applicable to one's project?

Thank you!

**Comment by mattbrannon** [comment]
This extension is meant for anyone who wants to enjoy the benefits of using prettier without also having to adhere to prettier's very opinionated formatting choices. For example - Prettier will always and forever format `if ... else` blocks like so:

```js
if (condition) {
  console.log('condition is true')
} else {
  console.log('condition is false')
}
```

I will always and forever be opposed to this type of formatting and much prefer:

```js
if (condition) {
  console.log('condition is true')
}
else {
  console.log('condition is false')
}
```

This extension allows my code to be formatted as I want every time a file is saved. You **don't** have to be using prettier-eslint in your project. That's what the extension does. You **do** need to have prettier and eslint installed in your project (not the extensions but the npm packages). Though the eslint extension is helpful in that it gives you visual indicators when your code breaks any linting rules. If you're using this extension (vs-code-prettier-eslint) I would suggest **not** having the prettier extension installed because it's redundant and quite large. 

Hope that makes sense :)

**Comment by DanKaplanSES** [comment]
@mattbrannon 
> Hope that makes sense :)

I think that makes _a lot_ of sense, so much so, I think it should be added near the top of the readme. For example, the first sentence says, "A Visual Studio Code Extension to format JavaScript and TypeScript code using the [prettier-eslint](https://github.com/prettier/prettier-eslint) package." In my opinion, that's a technical detail that _implies_ the opposite of your statement: "You don't have to be using prettier-eslint in your project. That's what the extension does."

Don't get me wrong, I'm aware that most of your reply is in the readme already. The issue is that the information is spread across the entire doc, whereas, IMHO, it's worth having in the initial summary.

**Comment by DanKaplanSES** [comment]
@mattbrannon thoughts? Worthy of a PR?

**Comment by idahogurl** [comment]
@DanKaplanSES Feel free to make a PR

**Comment by DanKaplanSES** [comment]
> @DanKaplanSES Feel free to make a PR

Thanks! I'll give it my best shot when I have more time. Sorry for not being more proactive, but I haven't actually used this extension, so I didn't feel confident about doing so until now.
