### ISSUE TITLE
Changes to prettier config require restart before taking effect

### ISSUE THREAD

**Issue by mattbrannon** [idahogurl/vs-code-prettier-eslint#43]
**Describe the bug**
When using the extension, changes to a project's prettier configuration only take effect after restarting vscode or restarting the extension host. (Open command palette, type restart and look for "Developer: Restart Extension Host")

**To Reproduce**
I made a [small repo](https://github.com/mattbrannon/prettier-eslint-example) to document the issue.

- clone the repo linked above and install dependencies
- make a change to the .prettierrc.json
- go into index.js and try to format the document

The updated prettier configuration is not used when formatting the document until the extension host is restarted.

**Expected behavior**
I expect the document to be formatted with the updated configuration without needing to restart

**Versions:**
- VS Code Prettier ESLint extension: 5.0.3
- Visual Studio Code: 1.68.1 
- Node: 16.13.0
- Package Manager: yarn 1.22.10
- prettier: 2.7.1
- eslint: 8.18.0

**System Specifications:**
- OS: MacOS Mojave 10.14.6
- Processor: 2.2 GHz Intel Core i7
- RAM Size: 8 GB 1600 MHz DDR3

**Comment by LovesLolita** [comment]
5.0.3 It doesn't work. I wonder why it doesn't work at all     >_<

**Comment by idahogurl** [comment]
@LovesLolita Could you provide your ESLint config?

**Comment by idahogurl** [comment]
@mattbrannon It's because of caching. The `prettier-eslint` package uses `prettier.resolveConfig` ([docs](https://prettier.io/docs/en/api.html#prettierresolveconfigfilepath--options)) to get the Prettier config file. You have to pass `useCache` as false to disable the behavior. Caching improves the performance but like you said you have to restart the editor. 

The only way to fix it would be to put a watcher on the Prettier config file and have the `prettier-eslint` package update to accept the option to disable it. A lot of work for something that can be remedied with a restart unless you have any ideas? 🙂

**Comment by mattbrannon** [comment]
@idahogurl Thanks for the info. I wasn't sure if it was due to the something in the `prettier-eslint` package, the extension or my setup. If this is expected and improves performance then there's not much to gain from a fix aside from not having to restart the editor which really isn't much of a problem.

I did find something else but I'll open a new issue for that. Closing this one.

**Comment by fmerlett-globality** [comment]
Might it make sense to have a command available from the command palette that would restart this specific extension or at least trigger a refetch of config files? The ESLint VSCode extension has such a command, as does the TypeScript VSCode extension, but it doesn't look like this extension has anything like that.

**Comment by finnmerlett** [comment]
Might it make sense to have a command available from the command palette that would restart this specific extension or at least trigger a refetch of config files? The ESLint VSCode extension has such a command, as does the TypeScript VSCode extension, but it doesn't look like this extension has anything like that.

**Comment by idahogurl** [comment]
@finnmerlett Looks like there's "Restart Extension Host" in the command palette (CMD + SHIFT + P). I wonder if I can programmatically call that command. Now that I think about it even a watcher won't work because the prettier instance that `prettier-eslint` creates is not accessible outside the package.

**Comment by finnmerlett** [comment]
@idahogurl I probably wouldn't take that approach, since as far as I can tell the extension host is responsible for the running of all extensions, and restarting all of them can take a while - so probably not feasible to do on every change of the config file. Is there a command that could be implemented inside the extension itself to restart and refetch config files? This seems to be what the TS services extension does.

**Comment by idahogurl** [comment]
@finnmerlett Good point. I'm pretty sure refetching the config files won't work because I'd need a new Prettier instance. I don't have access to the prettier instance created in `prettier-eslint`. I'd have to dig into the TS services extension to see how it restarts. Do you have a permalink to that code?

**Comment by finnmerlett** [comment]
So the TS services extension is actually a built-in one, so I can't find a link to it. However ESLint also has a command to restart its own service, and the link to that code is https://github.com/Microsoft/vscode-eslint
